imports:
    - { resource: config_dev.yml }

doctrine:
    dbal:
        default_connection: default

        connections:
            default:
                driver:  pdo_sqlite
                user:    test
                path:    %kernel.root_dir%/sqlite.db.cache
                #memory: true
                charset: utf8
    orm:
        entity_managers:
            default:
                metadata_cache_driver: apcu
                query_cache_driver:    apcu
                result_cache_driver:   apcu

framework:
    test: ~