services:

    api_exception_listener:
        class: App\BlogBundle\EventListener\ApiExceptionListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }

    redis_connection:
        class: App\BlogBundle\Service\Impl\RedisConnectionServiceImpl

    cache_redis:
        class: App\BlogBundle\Service\Impl\CacheServiceImpl
        arguments: ['@redis_connection']

    paginator:
        class: App\BlogBundle\Service\Impl\PaginatorServiceImpl
        tags:
            - { name: knp_paginator.injectable, paginator: knp_paginator }

    article:
        class: App\BlogBundle\Service\Impl\ArticleServiceImpl
        arguments: [
              '@doctrine.orm.entity_manager',
              '@paginator',
              '@cache_redis',
              '@form.factory',
              '@event_dispatcher',
              '@serializer'
              ]

    page_views:
        class: App\BlogBundle\Service\Impl\PageViewsImpl
        arguments: [
              '@doctrine.orm.entity_manager',
              '@serializer'
              ]

    page_views_consumer:
        class: App\BlogBundle\RabbitMq\Consumer\PageViewsConsumer
        arguments: [
              '@monolog.logger.rabbitmq_log',
              '@event_dispatcher',
              '@page_views'
              ]

    page_views_listener:
        class: App\BlogBundle\EventListener\PageViewsListener
        arguments: [
              '@page_views',
              '@monolog.logger.rabbitmq_log'
              ]
        tags:
            - { name: kernel.event_subscriber }
