services:
#    app_blog.example:
#        class: App\BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app_blog.api_exception_listener:
        class: App\BlogBundle\EventListener\ApiExceptionListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }

    redis_connection:
        class: App\BlogBundle\Service\Impl\RedisConnectionServiceImpl

    cache_redis:
        class: App\BlogBundle\Service\Impl\CacheServiceImpl
        arguments: ['@redis_connection']

    paginator:
        class: App\BlogBundle\Service\Impl\PaginatorServiceImpl
        tags:
            - { name: knp_paginator.injectable, paginator: knp_paginator }

    article:
        class: App\BlogBundle\Service\Impl\ArticleServiceImpl
        arguments: [
              '@doctrine.orm.entity_manager',
              '@paginator',
              '@cache_redis',
              '@form.factory',
              '@event_dispatcher',
              '@serializer'
              ]