services:
#    app_blog.example:
#        class: App\BlogBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    app_blog.api_exception_listener:
        class: App\BlogBundle\EventListener\ApiExceptionListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }

    cache_redis:
        class: App\BlogBundle\Service\impl\CacheServiceImpl
        arguments: []